# Generated by Django 2.1.2 on 2018-10-26 18:00

from django.db import migrations

from accounts.models import AccoutUser


def create_default_user(apps, schema_editor):
    usr = AccoutUser(
        username='ad',
        is_staff=True,
        is_superuser=True,
    )
    usr.set_password('Adm123456')
    usr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_user,
            lambda x, y: (x, y)
        )
    ]
